baseURL: https://sourcebots.co.uk
languageCode: en-gb
title: SourceBots
theme: mainroad

params:
    themeColour: "#4B35B3"
    subtitle: Exciting robotics challenges for teams of young people
    description: SourceBots Robotics — exciting robotics challenges for teams of young people
    readmore: true
    opengraph: true
    show_stream: true
    competition_livestream_url: https://www.facebook.com/SUSUtv/videos/vb.159049780794219/1891818877517292/?type=3&theater
    postSections:
      - blog
    widgets:
        search: false
        recent_articles: true
        tags: true
        social_github: sourcebots
        social_twitter: sourcebotscomp
        social_facebook: sourcebots
        events: true

outputFormats:
  ical:
    name: "ics"
    mediaType: "text/calendar"


outputs:
  home:
    - "html"
    - "rss"
  section:
    - "html"
    - "rss"
    - "ics"

menu:
  main:
    - name: Documentation
      url: https://docs.sourcebots.co.uk

buildFuture: true
enableRobotsTXT: true
disableHugoGeneratorInject: true
enableEmoji: true
pygmentsCodeFencesGuessSyntax: true

disableKinds:
  - taxonomy
  - taxonomyTerm
